import type { FeedGroup } from '../app/types/feed'
// 友链检测 CLI 需要使用显式导入和相对路径
import { myFeed } from '../blog.config'
// eslint-disable-next-line unused-imports/no-unused-imports
import { getFavicon, getGithubAvatar, getGithubIcon, getOciqGroupAvatar, getOicqAvatar, OicqAvatarSize } from './utils/img'

export default [
	// #region 推荐友链
	{
		name: '『推荐友链』',
		desc: '本站推荐的友链',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: 'LiuShen',
				sitenick: '清羽 〄 飞扬',
				title: '清羽飞扬',
				desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
				link: 'https://blog.liushen.fun/',
				feed: 'https://blog.liushen.fun/atom.xml',
				icon: '/image/LinkCover/LiuShen.avif',
				avatar: getOicqAvatar('3162475700'),
				archs: ['Hexo', '服务器'],
				date: '2025-03-15',
				comment: '',
			},{
				author: '『轻笑Chuckle』',
				sitenick: '轻笑Chuckle',
				title: '轻笑Chuckle',
				desc: '漫天倾尘风中轻笑',
				link: 'https://www.qcqx.cn',
				feed: 'https://www.qcqx.cn/atom.xml',
				icon: 'https://www.qcqx.cn/head.webp',
				avatar: 'https://www.qcqx.cn/head.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2025-03-19',
				comment: '',
			},{
				author: '贰猹',
				sitenick: '贰猹',
				title: '贰猹的小窝',
				desc: '用这生命中的每一秒，给自己一个不后悔的未来',
				link: 'https://noionion.top/',
				feed: 'https://noionion.top/rss.xml',
				icon: 'https://pub-noionion.oss-cn-hangzhou.aliyuncs.com/head.jpg',
				avatar: 'https://pub-noionion.oss-cn-hangzhou.aliyuncs.com/head.jpg',
				archs: ['Hexo', 'Vercel'],
				date: '2025-03-19',
				comment: '',
			},{
				author: '安知鱼',
				sitenick: '安知鱼',
				title: '安知鱼',
				desc: '生活明朗，万物可爱',
				link: 'https://blog.anheyu.com/',
				feed: 'https://blog.anheyu.com/rss.xml',
				icon: 'https://npm.elemecdn.com/anzhiyu-blog-static@1.0.4/img/avatar.jpg',
				avatar: 'https://npm.elemecdn.com/anzhiyu-blog-static@1.0.4/img/avatar.jpg',
				archs: ['Hexo', '服务器'],
				date: '2025-03-19',
				comment: '',
			},{
				author: '王先森',
				sitenick: '王先森',
				title: '王先森',
				desc: '运维与安全从业者！',
				link: 'https://www.boysec.cn',
				feed: 'https://www.boysec.cn/atom.xml',
				icon: 'https://cdn.boysec.cn/medias/avatar.jpg',
				avatar: 'https://cdn.boysec.cn/medias/avatar.jpg',
				archs: ['Hexo', 'Vercel'],
				date: '2025-03-19',
				comment: '',
			},
		],
	},
	// #endregion
	// #region 2026
	{
		name: '『2026』',
		desc: '在2026年添加友链的朋友们',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '夜轻Blog',
				sitenick: '夜轻Blog',
				title: '夜轻Blog',
				desc: '一个人',
				link: 'http://blog.yeqing.net/',
				feed: 'http://blog.yeqing.net/atom.xml',
				icon: 'https://list.yppp.net/d/cos/yeqing.webp',
				avatar: getOicqAvatar('2829470170'),
				archs: ['Hexo', 'Vercel'],
				date: '2026-07-16',
				comment: '',
			},{
				author: '天翔TNXG',
				sitenick: '天翔TNXG',
				title: '天翔TNXG',
				desc: '一个人',
				link: 'https://www.tnxg.moe/',
				feed: 'https://www.tnxg.moe/atom.xml',
				icon: 'https://api-space.tnxg.top/avatar?s=qq',
				avatar: getOicqAvatar('2271225249'),
				archs: ['Next.js', 'Vercel'],
				date: '2026-07-16',
				comment: '',
			},{
				author: 'Pinpe',
				sitenick: 'Pinpe',
				title: 'Pinpe',
				desc: '一个人',
				link: 'https://pinpe.top/',
				feed: 'https://pinpe.top/atom.xml',
				icon: 'https://pinpe.top/_astro/head.6aCCsxCR_Z18fyOl.webp',
				avatar: getOicqAvatar('3776284379'),
				archs: ['Next.js', 'Vercel'],
				date: '2026-07-16',
				comment: '',
			},
		]
	},
	// #endregion
	// #region 2025
	{
		name: '『2025』',
		desc: '在2025年添加友链的朋友们',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '安小歪',
				sitenick: '安小歪',
				title: '安小歪',
				desc: '记住你！自己！',
				link: 'https://blog.anxw.cn/',
				feed: '',
				icon: '/image/LinkCover/Anxy.avif',
				avatar: '/image/LinkCover/Anxy.avif',
				archs: ['Hexo', 'Vercel'],
				date: '2025-03-19',
				comment: '',
			},{
				author: 'Leonus',
				sitenick: 'Leonus',
				title: 'Leonus',
				desc: '进一寸有进一寸的欢喜。',
				link: 'https://blog.leonus.cn/',
				feed: 'https://blog.leonus.cn/atom.xml',
				icon: 'https://q1.qlogo.cn/g?b=qq&nk=990320751&s=5',
				avatar: 'https://q1.qlogo.cn/g?b=qq&nk=990320751&s=5',
				archs: ['Hexo', 'Vercel'],
				date: '2025-04-19',
				comment: '',
			},{
				author: 'Ariasaka',
				sitenick: 'Ariasakaの小窝',
				title: 'Ariasakaの小窝',
				desc: '人有悲欢离合 月有阴晴圆缺',
				link: 'https://blog.yaria.top',
				feed: '',
				icon: '/image/LinkCover/Ariasaka.avif',
				avatar: '/image/LinkCover/Ariasaka.avif',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-03-25',
				comment: '',
			},{
				author: '别亦难',
				sitenick: '别亦难',
				title: '别亦难',
				desc: '准时不定期更新',
				link: 'https://lazyingman.cn',
				feed: '',
				icon: '/image/LinkCover/LazyingMan.avif',
				avatar: '/image/LinkCover/LazyingMan.avif',
				archs: ['Hexo', 'Vercel'],
				date: '2025-03-30',
				comment: '',
			},{
				author: '前尘小筑',
				sitenick: '前尘小筑',
				title: '前尘小筑',
				desc: '虽多尘色染，犹见墨痕浓',
				link: 'https://mnchen.cn/',
				feed: '',
				icon: '/image/LinkCover/MnoChen.avif',
				avatar: '/image/LinkCover/MnoChen.avif',
				archs: ['Hexo', 'Vercel'],
				date: '2025-04-30',
				comment: '',
			},{
				author: '葱苓sama',
				sitenick: '葱苓小筑',
				title: '葱苓小筑',
				desc: 'Don t worry, be happy',
				link: 'https://blog.ciraos.top',
				feed: '',
				icon: '/image/LinkCover/Ciraos.avif',
				avatar: '/image/LinkCover/Ciraos.avif',
				archs: ['Hexo', 'Vercel'],
				date: '2025-03-19',
				comment: '',
			},{
				author: '❖星港◎Star☆',
				sitenick: '❖星港◎Star☆',
				title: '❖星港◎Star☆',
				desc: '以博客记录生活与热爱！',
				link: 'https://blog.starsharbor.com',
				feed: '',
				icon: '/image/LinkCover/StarsharBor.avif',
				avatar: '/image/LinkCover/StarsharBor.avif',
				archs: ['Hexo', 'Vercel'],
				date: '2025-03-19',
				comment: '',
			},{
				author: '青序栈',
				sitenick: '',
				title: '青序栈',
				desc: '青序成栈·向简而生',
				link: 'https://www.qixz.cn/',
				feed: 'https://www.qixz.cn/feed/',
				icon: 'https://www.qixz.cn/favicon.png',
				avatar: 'https://www.qixz.cn/favicon.png',
				archs: ['Hexo'],
				date: '2025-08-29',
				comment: '',
			}
		],
	},
	// #endregion
] satisfies FeedGroup[]
