import type { FeedGroup } from '../app/types/feed'
// 友链检测 CLI 需要使用显式导入和相对路径
import { myFeed } from '../blog.config'
// eslint-disable-next-line unused-imports/no-unused-imports
import { getFavicon, getGithubAvatar, getGithubIcon, getOciqGroupAvatar, getOicqAvatar, OicqAvatarSize } from './utils/img'

export default [
	// #region 高木同好
	{
		name: '高木同好',
		desc: '我们高木圈真是太有技术了.jpg',
		entries: [
			myFeed,
			{
				author: 'Ice Year',
				sitenick: 'の位面',
				title: 'Ice Year の位面',
				desc: 'Il n\'y a pas de hasard, il n\'y a que des rendez - vous',
				link: 'https://blog.iceyear.eu.org/',
				feed: 'https://blog.iceyear.eu.org/index.xml',
				icon: 'https://blog.iceyear.eu.org/img/avatar_hu_a03d367ff590d53f.webp',
				avatar: 'https://blog.iceyear.eu.org/img/avatar_hu_a03d367ff590d53f.webp',
				archs: ['Hugo', 'Cloudflare'],
				comment: '高木圈同好，技术引路人，爱好Gal/折腾。',
			},
			{
				author: '辰灿汐',
				sitenick: '的小站',
				title: '辰灿汐的小站',
				desc: '以自己的一切面对世间',
				link: 'https://aurorainic.top/',
				feed: 'https://aurorainic.top/feed',
				icon: 'https://pic.imgdb.cn/item/66be3143d9c307b7e9dbc86e.jpg',
				avatar: 'https://pic.imgdb.cn/item/66be3143d9c307b7e9dbc86e.jpg',
				archs: ['WordPress', '服务器'],
				comment: '高木圈同好/支柱，木创社创立者，技术方面也有不少探讨。',
			},
			{
				author: 'WaterApple',
				title: '糖の小站',
				desc: '世界，您好！',
				link: 'https://waterapple09.com/',
				feed: 'https://waterapple09.com//feed',
				icon: 'https://cravatar.cn/avatar/5f8cf4ce23190a932b1995494e53f1c2?s=400&d=mp',
				avatar: 'https://cravatar.cn/avatar/5f8cf4ce23190a932b1995494e53f1c2?s=400&d=mp',
				archs: ['WordPress', '服务器'],
				comment: '高木圈同好，早期探索技术财务支持神秘大佬。',
			},
			{
				author: '南栀',
				sitenick: 'Space',
				title: '南栀Space',
				desc: '葡萄何时才熟透，你要静候再静候。',
				link: 'https://blog.litkg3.com',
				icon: getGithubIcon('litkg3'),
				avatar: getGithubAvatar('litkg3'),
				archs: ['Next.js', '服务器'],
				comment: '高木圈同好，大学生，技术折腾/生活都有交流。',
			},
			{
				author: '陈郑逸',
				sitenick: '领域',
				title: '陈郑逸领域',
				desc: '岁月如歌，荏苒同行！',
				link: 'https://fujianprovince.github.io/',
				icon: 'https://pic1.imgdb.cn/item/68ae992858cb8da5c8547d20.jpg',
				avatar: 'https://pic1.imgdb.cn/item/68ae992858cb8da5c8547d20.jpg',
				archs: ['HTML', 'GitHub Pages'],
				comment: '高木圈同好，大学生，学业之外，所采众长。',
			},
		],
	},
	// #endregion

	// #region 值得推荐
	{
		name: '值得推荐',
		desc: '个人觉得很有意思和存在创新的博客站点。',
		entries: [
			{
				author: 'RavelloH',
				sitenick: 'Blog',
				title: 'RavelloH Blog',
				desc: '广袤互联网中的一隅静处。',
				link: 'https://ravelloh.top',
				feed: 'https://ravelloh.top/feed.xml',
				icon: 'https://ravelloh.top/avatar.jpg',
				avatar: 'https://ravelloh.top/avatar.jpg',
				archs: ['Next.js', 'Vercel'],
				comment: '采用自研Next.js博客系统，与我也有些许交流探讨。',
			},
			{
				author: 'iMaeGoo',
				sitenick: '空间站',
				title: '虹墨空间站',
				desc: '虹墨空间站',
				link: 'https://www.imaegoo.com/',
				feed: 'https://www.imaegoo.com/atom.xml',
				icon: 'https://www.imaegoo.com/favicon.ico',
				avatar: 'https://www.imaegoo.com/images/avatar.jpg',
				archs: ['Hexo', '国内 CDN'],
				comment: 'Twikoo评论系统作者。',
			},
			{
				author: 'GTX690战术核显卡导弹',
				sitenick: '猫窝',
				title: 'GTX690战术核显卡导弹的猫窝',
				desc: '一个过气UP的博客，喜欢计算机技术，希望交个朋友。',
				link: 'https://nekopara.uk/',
				icon: 'https://logo.nekopara.uk/logo.jpg',
				avatar: 'https://logo.nekopara.uk/logo.jpg',
				archs: ['Typecho', '服务器'],
				comment: '以前（大概初高中）的时候有看过 UP 主的视频，有点意思。',
			},
			{
				author: '晓空',
				sitenick: '空域',
				title: '晓空blog',
				desc: '探索更大的世界',
				link: 'https://blog.moeworld.tech/',
				feed: 'https://blog.moeworld.tech/feed/',
				icon: 'https://blog.moeworld.tech/wp-content/uploads/2024/08/cropped-favicon-32x32.png',
				avatar: 'https://blog.moeworld.tech/wp-content/themes/kratos-pjax-master/static/images/photo.jpg',
				archs: ['WordPress', 'Cloudflare'],
				comment: '技术折腾笔记。',
			},
			{
				author: '纸鹿本鹿',
				title: '纸鹿摸鱼处',
				desc: '纸鹿至麓不知路，支炉制露不止漉',
				link: 'https://blog.zhilu.site/',
				icon: 'https://www.zhilu.site/api/avatar.png',
				avatar: 'https://www.zhilu.site/api/avatar.png',
				archs: ['Nuxt', 'Vercel'],
				comment: 'Clarity 主题作者，前端大神是也。',
			},
			{
				author: 'Kegongtang',
				title: 'Kegongtang',
				desc: 'Blogger / Technophile / Student',
				link: 'https://kegongteng.cn/',
				icon: 'https://weavatar.com/avatar/0b01396273cca253aa6876c020449b655a9cc12e75f921b38ac088569e814b5e',
				avatar: 'https://weavatar.com/avatar/0b01396273cca253aa6876c020449b655a9cc12e75f921b38ac088569e814b5e',
				archs: ['Next.js', 'Netlify'],
			},
			{
				author: '广树',
				sitenick: '维基萌',
				title: '维基萌',
				desc: '萌即是正义！时不时分享一些ACG活动记录与有趣代码的小站！',
				link: 'https://www.wikimoe.com/',
				icon: 'https://www.wikimoe.com/upload/siteImg/siteFavicon.png',
				avatar: getGithubAvatar('eeg1412'),
				archs: ['Nuxt', '服务器'],
				comment: 'Wikimoe 系统作者，ACG 爱好者。',
			},
			{
				author: 'RefactX Project',
				title: 'Refactored',
				desc: '形体是简单而纯粹的，它不是完整的群体，每个形体都指向其复杂性，并最终被复杂性联系在一起。',
				link: 'https://www.refact.cc',
				icon: 'https://refact.cc/avatar.png',
				avatar: 'https://refact.cc/avatar.png',
				archs: ['Astro', 'Vercel'],
				comment: '很有设计感，RefactX 博客主题作者。',
			},
		],
	},
	// #endregion

	// #region 网上邻居
	{
		name: '网上邻居',
		desc: '哔——啵——电波通讯中，欢迎常来串门。',
		entries: [
			{
				author: 'Kurococ Liu',
				desc: '被子外面很危险！',
				link: 'https://blog.lkurococ.top/',
				feed: 'https://blog.lkurococ.top/feed',
				icon: 'https://blog.lkurococ.top/_next/image?url=https%3A%2F%2Fcdn.lkurococ.top%2F2024%2F10%2F600292e5a454abe3b6e653801834fb60.jpg&w=384&q=75',
				avatar: 'https://blog.lkurococ.top/_next/image?url=https%3A%2F%2Fcdn.lkurococ.top%2F2024%2F10%2F600292e5a454abe3b6e653801834fb60.jpg&w=384&q=75',
				archs: ['Next.js', '服务器'],
				comment: '学生，记录生活思考。',
			},
			{
				author: 'AkiDay',
				desc: '永恒秋日之星',
				link: 'https://blog.akiday.com/',
				feed: 'https://blog.akiday.com/feed/',
				icon: 'https://blog.akiday.com/imgapi/profile.webp',
				avatar: 'https://blog.akiday.com/imgapi/profile.webp',
				archs: ['WordPress', '服务器'],
				comment: '目前仍在普通地读书。热爱物理，尤其是天文方向。',
			},
			{
				author: '小雅',
				sitenick: '星辰角落',
				title: '星辰角落',
				desc: '热爱记录生活',
				link: 'https://ihello.cc',
				feed: 'https://ihello.cc/rss.xml',
				icon: 'https://s2.loli.net/2025/02/22/IYKOhlGQmz137jr.png',
				avatar: 'https://s2.loli.net/2025/02/22/IYKOhlGQmz137jr.png',
				archs: ['Halo', '服务器'],
			},
			{
				author: '洛雨',
				sitenick: 'の小站',
				title: '洛雨の小站',
				desc: '历史终将证明一切',
				link: 'https://luotianyi.eu/',
				feed: 'https://luotianyi.eu/feed/',
				icon: 'https://luotianyi.eu/wp-content/uploads/2024/05/1715104252-v2-be101b87e6774cf029ce05ecff8f2b33_r-scaled-e1715104292489.jpg',
				avatar: 'https://luotianyi.eu/wp-content/uploads/2024/05/1715104252-v2-be101b87e6774cf029ce05ecff8f2b33_r-scaled-e1715104292489.jpg',
				archs: ['WordPress', '服务器'],
				comment: '超级喜欢洛天依~~~',
			},
			{
				author: '千乐铃音',
				desc: '我在等风，也在等你。',
				title: '风月琉璃',
				link: 'https://miui.ink',
				feed: 'https://miui.ink/feed/',
				icon: 'https://miui.ink/wp-content/uploads/2023/11/im_1.jpg',
				avatar: 'https://miui.ink/wp-content/uploads/2023/11/im_1.jpg',
				archs: ['WordPress', '服务器'],
			},
			{
				author: 'AI悦创',
				title: '别碰我的镜头盖',
				desc: '世界那么大，我想去看看',
				link: 'https://blog.bornforthis.cn/',
				feed: 'https://blog.bornforthis.cn/atom.xml',
				icon: 'https://weavatar.com/avatar/d2262986371318821a2cfe4dc37a18bd62af3e7e5d531301c87f6066a483faa0?d=letter&letter=A',
				avatar: 'https://weavatar.com/avatar/d2262986371318821a2cfe4dc37a18bd62af3e7e5d531301c87f6066a483faa0?d=letter&letter=A',
				archs: ['Hexo', '国内 CDN'],
			},
			{
				author: '星港',
				sitenick: 'Star☆',
				title: '❖星港◎Star☆',
				desc: '以博客记录生活与热爱！',
				link: 'https://blog.starsharbor.com/',
				icon: 'https://bu.dusays.com/2025/04/11/67f92f6fcfb26.webp',
				avatar: 'https://bu.dusays.com/2025/04/11/67f92f6fcfb26.webp',
				archs: ['Hexo', 'Vercel'],
			},
			{
				author: '鹊楠',
				sitenick: '小窝',
				title: '鹊楠の小窝',
				desc: '世界那么大，我想去看看。',
				link: 'https://blog.quenan.cn/',
				icon: 'https://i.p-i.vip/43/20240913-66e403f2331ec.webp',
				avatar: 'https://i.p-i.vip/43/20240913-66e403f2331ec.webp',
				archs: ['Vue', '服务器'],
			},
			{
				author: '弈鸣小筑',
				sitenick: 'Blog',
				title: '弈鸣小筑Blog',
				desc: '功不唐捐，玉汝于成。',
				link: 'https://blog.ymhut.cn/',
				icon: 'https://blog.ymhut.cn/upload/b_0cebb0c983fc740efd61c424db4e140b.jpg',
				avatar: 'https://blog.ymhut.cn/upload/b_0cebb0c983fc740efd61c424db4e140b.jpg',
				archs: ['WordPress', '服务器'],
			},
			{
				author: 'LeonXie',
				sitenick: 'の小窝',
				title: 'LeonXieの小窝',
				desc: '保持热爱，奔赴山海！',
				link: 'https://www.leonxie.cn',
				icon: 'https://www.leonxie.cn/upload/avatar.jpg',
				avatar: 'https://www.leonxie.cn/upload/avatar.jpg',
				archs: ['Halo', '服务器'],
			},
			{
				author: 'Hikaru',
				sitenick: 'Lab',
				title: 'Hikaru Lab',
				desc: '即使是人造的记忆，也有它存在的价值',
				link: 'https://www.mengxiblog.top/',
				icon: 'https://img-cn.static.isla.fan/2025/10/19/68f4824b7c228.png',
				avatar: 'https://img-cn.static.isla.fan/2025/10/19/68f4824b7c228.png',
				archs: ['Vercel', 'Astro'],
			},
			{
				author: '栖童',
				sitenick: 'の小站',
				title: '栖童の小站',
				desc: '越努力,越幸运',
				link: 'https://blog.linux-qitong.top',
				icon: 'https://blog.linux-qitong.top/img/avatar.webp',
				avatar: 'https://blog.linux-qitong.top/img/avatar.webp',
				archs: ['Nuxt', 'Vercel'],
			},
			{
				author: 'Shiro',
				title: 'Shiro',
				desc: '夙兴夜，勤不怠。',
				link: 'https://shiro.love',
				icon: 'https://assets.moedev.cn/blog/photo/user/head.jpg!webp',
				avatar: 'https://assets.moedev.cn/blog/photo/user/head.jpg!webp',
				archs: ['服务器', 'Next.js'],
			},
			{
				author: '御坂秋生',
				sitenick: 'の小窝',
				title: '御坂秋生の小窝',
				desc: '不努力就只能听到别人的好消息',
				link: 'https://www.akio.top/',
				feed: 'https://www.akio.top/feed/',
				icon: 'https://webstatic.akio.top/user/NiuBoss123.jpg',
				avatar: 'https://webstatic.akio.top/user/NiuBoss123.jpg',
				archs: ['Next.js', '服务器'],
			},
			{
				author: '存在证明的',
				sitenick: '阿远',
				title: '存在证明的阿远',
				desc: '一个兴趣广泛的小废物',
				link: 'https://ayuan.ink/',
				icon: 'https://ayuan.ink/wp-content/uploads/2024/08/IMG_808720240826-150111.jpg',
				avatar: 'https://ayuan.ink/photos/picture/20251226220141038.jpg',
				archs: ['Astro', 'Vercel'],
			},
			{
				author: '懋和道人',
				sitenick: 'Dao',
				title: '懋和道人',
				desc: '懋和道人',
				link: 'https://www.dao.js.cn',
				feed: 'https://www.dao.js.cn/feed/',
				icon: 'https://cn.cravatar.com/avatar/37d41e2b550633a30f5d41de61c1aa92?s=400&r=G&d=mp&ver=1754413756',
				avatar: 'https://cn.cravatar.com/avatar/37d41e2b550633a30f5d41de61c1aa92?s=400&r=G&d=mp&ver=1754413756',
				archs: ['HTML', '国内 CDN'],
				comment: '李懋和，俗名李栋梁。书法、国画爱好者，互联网安全与前端建设者。',
			},
			{
				author: 'LHL\'s Blog',
				sitenick: 'LHL',
				title: 'LHL\'s Blog',
				desc: 'LHL\'s Blog',
				link: 'https://blog.lhl.one',
				icon: 'https://cdn.sa.net/2025/04/18/KXpf8u5SQYNPkA3.jpg',
				avatar: 'https://cdn.sa.net/2025/04/18/KXpf8u5SQYNPkA3.jpg',
				archs: ['HTML', '国内 CDN'],
				comment: '想把海洋里所有鱼都握在手里，把森林里里所有花都插在心头.',
			},
			{
				author: 'VnYzm 的博客',
				sitenick: 'VnYzm',
				title: 'VnYzm 的博客',
				desc: 'VnYzm 的博客',
				link: 'https://vnyzm.top',
				icon: 'https://vnyzm.top/img/profile.jpg',
				avatar: 'https://vnyzm.top/img/profile.jpg',
				archs: ['HTML', '国内 CDN'],
				comment: '分享技术心得和摸鱼感想 ',
			},
			{
				author: '倪哥买提大巴扎',
				sitenick: '',
				title: '倪哥买提大巴扎',
				desc: '倪哥买提大巴扎',
				link: 'https://www.gnix807.cn/',
				icon: 'https://img.gnix807.cn/Logo_small.jpeg',
				avatar: 'https://img.gnix807.cn/Logo_small.jpeg',
				archs: ['HTML', '国内 CDN'],
				comment: '烤肉man的日常',
			},
			{
				author: '六月是只猫',
				sitenick: '',
				title: '六月是只猫',
				desc: '我年轻，我傲娇。',
				link: 'https://www.lyszm.com',
				icon: 'https://cravatar.com/avatar/f9c8534573959f75b8b00ffa37f39687?&d=mm&s=200',
				avatar: 'https://cravatar.com/avatar/f9c8534573959f75b8b00ffa37f39687?&d=mm&s=200',
				archs: ['Typecho', '服务器'],
				comment: '站点禁止开发者模式访问判断过于敏感，正常访问仍无法访问，建议修复。',
			},
			{
				author: '萌言Moey',
				sitenick: '一言',
				title: '萌言Moey',
				desc: '一个萌萌の句子收藏站',
				link: 'https://moey.cn/',
				icon: 'https://pic.imgdb.cn/item/64a7c06e1ddac507ccdfe43f.jpg',
				avatar: 'https://pic.imgdb.cn/item/64a7c06e1ddac507ccdfe43f.jpg',
				archs: ['HTML', '国内 CDN'],
				comment: '一个一言站点，萌言萌句汇聚于此。',
			},
		],
	},
	// #endregion
] satisfies FeedGroup[]
